### ISSUE TITLE
Instalación de la aplicación

### ISSUE THREAD

**Issue by aula2030** [aula2030/educacion#5]
Buenas!

Ayer, después de aceptar el primer PR, me puse a instalar en mi local lo que había. Es el paso previo a subirlo a educacion.pista7.net que es donde está el servidor de desarrollo.

Estaría bien que en el README.md hubiera cuatro detalles de cómo instalarlo. Como la instalación se hace a partir de Github con un grav funcionando, en teoría tenía que seguir estos pasos (https://learn.getgrav.org/16/basics/installation#option-3-install-from-github). Hice:

1. Pull de dev. Ok.
2. `composer install`. Ok
3. `php bin/grav install`. Y el resultado fue éste:

![grav_install](https://user-images.githubusercontent.com/66673634/93016789-038a1e80-f5c4-11ea-8d59-5a82e3b1badf.png)

4. ???? Al comprobar si funcionaba algo a través del browser, había un mensaje simliar a "Tema Learn2 no está instalado". Mirando el .gitignore hay esto:

```
user/themes/*
!user/themes/.*
```

Lo que a la práctica significa que no se guarda el tema. Lo que a la práctica significa que el tema se tiene que instalar a parte. Lo que a la práctica significa que si tocas algo del tema, habrá que cambiarle el nombre y cambiar el .gitignore para que sí se guarde en el repo.

4. Instalar el tema: `bin/gpm install learn2`
5. El resultado es esta página, que supongo que se asemeja a lo que tienes tú:

![home](https://user-images.githubusercontent.com/66673634/93016853-70051d80-f5c4-11ea-9704-d8dbc83df14b.png)

Así que hay que mirar eso del fichero .dependencies, por si hay que añadirlo al .gitignore. :+1:

**Comment by AbdellahEO** [comment]
hola @aula2030 !
Si, learn2 tiene ese formato, esto quiere decir que se debe guardar en el repositorio para evitar que se instale aparte.
Por otro lado, queda bien añadir en el README.md los pasos de la instalación 
👍

**Comment by aula2030** [comment]
@AbdellahEO En el repo solo debe ir lo que sea imprescindible! Si no se modifica nada del tema no hace falta ya que se puede instalar desde su propio repositorio. Solo habrá que especificar qué versión concreta se instala!

Si no hay cambios en el tema, solo hay que meter en el README. md que se debe instalar aparte :+1:

**Comment by AbdellahEO** [comment]
@aula2030 ,
De acuerdo 👍

**Comment by aula2030** [comment]
@AbdellahEO Buenas! Veo que en el README has copiado lo que pone en la docu de Grav. Pero no es eso exactamente, porque para instalar este repo no hace falta clonar del repo de Grav, solo hay que clonar este repositorio y ejecutar el install..... :disappointed: 

¿Lo has traducido con Google Translator? Pone "Instale las dependencias del proveedor a través del **compositor** :". Supongo que será la traducción de `composer`.

Piensa que eso lo leería un supuesto usuario que lo quisiera instalar en su servidor... Debe ser claro y conciso. ¡Y sin errores!

Más abajo pone: "cd ~/webroot/grav bin/grav installCopiar".... ¿installCopiar?

En general, te diría que hay que tener mucho cuidado con los detalles (eso está claro que no te lo has leído luego). Si esto lo ve alguien lo primero que pensaría es que lo han hecho deprisa y corriendo. Creo, vaya. La info sobre como instalar (y actualizar) el tema es irrelevante tal y como está (copiado del repo del tema). Simplemente explicando que se debe instalar el tema Learn2 y un enlace a su repo sería suficiente.

Lo que haría yo es probar de instalarlo desde cero (como si fuera un usuario cualquiera que se clona el repo en su PC) y ver los problemas que salen. Tal como te escribí yo, 1-2-3-4 pasos serían suficientes.

Ahora, con el plugin Login, supongo que habrá que hacer lo mismo, añadir un paso más de cómo se instala el plugin.

No te preocupes, ya lo actualizaré yo. Simplemente para que te des cuenta de que hay que tener cuidado de los detalles, y que ¡no vale copiar y pegar rápido y ya está! Supongo que me sale la vena de profe. :sweat_smile: 

Como te decía, deja el README, **ya lo actualizaré yo**. Pero tenlo en cuenta en general. Ya ves que tengo el ojo fino.

**Comment by AbdellahEO** [comment]
@aula2030,
Ah vaya ☹️! 
Si me di cuenta de que no esta 100% ( ha sido un copiar y pegar), pero lo tenía pendiente para modificar . 
No te preocupes ahora lo actualizo 🤗. 

Vale, lo tendré en cuenta profe 😊.
